In [1]:
import numpy as np

In [2]:
arr = [[1,2], [3,4]]
arr

[[1, 2], [3, 4]]

In [4]:
## Convert to numpy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [5]:
import torch

In [6]:
#convert to pytorch tensor

torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

In [9]:
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [10]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

## Numpy to Torch